"""Generate include/generated/openapi.h from openapi.yaml at build time.

Wired up via `extra_scripts = pre:tools/generate_openapi_header.py` so the
firmware always embeds the OpenAPI spec that is checked into the repository.
"""

import os


def _project_root():
    try:
        # run standalone: python3 tools/generate_openapi_header.py
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    except NameError:
        # imported by SCons (extra_scripts pre hook): no __file__ in scope
        Import("env")
        current = os.path.abspath(str(env.Dir(".")))
        while not os.path.exists(os.path.join(current, "platformio.ini")):
            parent = os.path.dirname(current)
            if parent == current:
                raise RuntimeError("could not locate project root (platformio.ini)")
            current = parent
        return current


PROJECT_ROOT = _project_root()
SPEC_PATH = os.path.join(PROJECT_ROOT, "openapi.yaml")
HEADER_DIR = os.path.join(PROJECT_ROOT, "include", "generated")
HEADER_PATH = os.path.join(HEADER_DIR, "openapi.h")

LINE_LENGTH = 96


def escape_char(ch):
    code = ord(ch)
    if ch == "\\":
        return "\\\\"
    if ch == '"':
        return '\\"'
    if ch == "\n":
        return "\\n"
    if ch == "\t":
        return "\\t"
    if ch == "\r":
        return "\\r"
    if 32 <= code < 127:
        return ch
    return "\\{:03o}".format(code)


def to_string_literal(text):
    # Split on escape-token boundaries only, so a backslash is never
    # stranded at the end of a source line (which would become a line
    # splice and break the string).
    tokens = [escape_char(ch) for ch in text]
    lines = []
    line = '    "'
    for token in tokens:
        if len(line) + len(token) > LINE_LENGTH:
            lines.append(line + '"')
            line = '    "'
        line += token
    lines.append(line + '"')
    return "\n".join(lines)


def main():
    with open(SPEC_PATH, "r", encoding="utf-8") as spec_file:
        spec = spec_file.read()

    header = (
        "// Auto-generated by tools/generate_openapi_header.py from openapi.yaml\n"
        "// Do not edit manually.\n"
        "\n"
        "#ifndef OPENAPI_H\n"
        "#define OPENAPI_H\n"
        "\n"
        "static const char openapiSpec[] =\n"
        + to_string_literal(spec)
        + ";\n"
        "\n"
        "#endif\n"
    )

    os.makedirs(HEADER_DIR, exist_ok=True)
    try:
        with open(HEADER_PATH, "r", encoding="utf-8") as existing_file:
            current = existing_file.read()
    except (FileNotFoundError, OSError):
        current = None
    if current != header:
        with open(HEADER_PATH, "w", encoding="utf-8") as out_file:
            out_file.write(header)
        print("openapi: generated " + os.path.relpath(HEADER_PATH, PROJECT_ROOT))
    else:
        print("openapi: " + os.path.relpath(HEADER_PATH, PROJECT_ROOT) + " up to date")


main()
